name: Deployment

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deployment:
    name: Connexion au serveur de prod
    runs-on: ubuntu-latest
    steps:
    - name: Connect with SSH to server
      uses: fifsky/ssh-action@master
      with:
        command: |
          sudo -i
          cd /home/debian/QuizzBattle
          eval "$(ssh-agent -s)"
          ssh-add /home/debian/.ssh/id_ed25519
          git stash
          git pull origin main --rebase
          git status
          git stash pop
          git status
          git log -10 --oneline
          cd /home/debian/QuizzBattle/QuizzBattle/front
          yarn
          yarn build-only
          cd /home/debian/QuizzBattle/QuizzBattle/back
          docker compose up -d
          yarn
          yarn pm2 stop dist/app.js
          yarn build
          yarn pm2 start dist/app.js
          yarn pm2 stop dist/migration.js
          yarn pm2 start dist/migration.js
          yarn pm2 status
        host: ${{ secrets.REMOTE_HOST }}
        user: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        pass: ${{ secrets.REMOTE_PWD }}